spring.application.name=reactive-api-postgres
server.port=${PORT:8080}

spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reactive_db}}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:${DB_USER:postgres}}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:${DB_PASSWORD:postgres}}

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
